#!/usr/bin/env perl

# suck - Pipe fitting that kills on silence.
#
# Copyright 2026 Billy Lyrical
# License: GPL
#


use strict;
use warnings;
use IO::Select;

my $silence_timeout = 0;
my $hard_timeout    = 0;
my $quiet           = 0;
my $ring_size       = 100;
my $verbose         = 0;

parse_args();

if (@ARGV) {
    exec_mode(@ARGV);
} else {
    filter_mode();
}

# --- modes ---

sub exec_mode {
    my (@cmd) = @_;
    pipe(my $rd, my $wr) or die "suck: pipe: $!\n";

    my $pid = fork();
    die "suck: fork: $!\n" unless defined $pid;

    if ($pid == 0) {
        close $rd;
        open(STDOUT, '>&', $wr) or exit 1;
        open(STDERR, '>&', STDOUT) or exit 1;
        close $wr;
        exec @cmd;
        warn "suck: exec @cmd: $!\n";
        exit 127;
    }

    close $wr;
    local $SIG{INT} = local $SIG{TERM} = sub { kill_child($pid); exit 130 };
    monitor($rd, $pid);
    close $rd;
    waitpid($pid, 0);
    exit($? >> 8);
}

sub filter_mode {
    local $SIG{INT} = local $SIG{TERM} = sub { exit 130 };
    monitor(\*STDIN, 0);
}

# --- core ---

sub monitor {
    my ($fh, $child_pid) = @_;
    my $sel = IO::Select->new($fh);
    my $last_output = time();
    my $start       = time();
    my @ring;
    my $partial     = '';
    local $| = 1;

    vprint("suck: pid=%d (silence=%ss hard=%ss)\n",
           $child_pid || $$, $silence_timeout, $hard_timeout) if $verbose;

    while (1) {
        my $wait = 1;
        if ($hard_timeout > 0) {
            my $left = $hard_timeout - (time() - $start);
            if ($left <= 0) {
                vprint("suck: hard timeout after %ss\n", $hard_timeout);
                kill_child($child_pid);
                dump_ring(\@ring, $partial);
                exit 124;
            }
            $wait = $left if $left < $wait;
        }

        my @ready = $sel->can_read($wait);

        if (@ready) {
            my $bytes = sysread($fh, my $buf, 8192);
            if (!defined $bytes || $bytes == 0) {
                push @ring, $partial if $partial ne '' && $quiet;
                last;
            }
            $last_output = time();

            if ($quiet) {
                $buf = $partial . $buf;
                my @lines = split /\n/, $buf, -1;
                $partial = pop @lines;
                push @ring, @lines;
                shift @ring while @ring > $ring_size;
            } else {
                print $buf;
            }
        }

        if ($silence_timeout > 0 && time() - $last_output > $silence_timeout) {
            vprint("suck: silence timeout after %ss\n", $silence_timeout);
            kill_child($child_pid);
            dump_ring(\@ring, $partial);
            exit 125;
        }
    }
}

# --- helpers ---

sub kill_child {
    my ($pid) = @_;
    return unless $pid;
    kill 'TERM', $pid;
    eval {
        local $SIG{ALRM} = sub { kill 'KILL', $pid };
        alarm 5;
        waitpid($pid, 0);
        alarm 0;
    };
}

sub dump_ring {
    my ($ring, $partial) = @_;
    return unless @$ring || $partial ne '';
    my @lines = @$ring;
    push @lines, $partial if $partial ne '';
    print STDERR "--- last " . scalar(@lines) . " lines ---\n";
    print STDERR "$_\n" for @lines;
}

sub vprint {
    printf STDERR @_;
}

sub parse_args {
    while (@ARGV && $ARGV[0] =~ /^-/) {
        my $arg = shift @ARGV;
        if    ($arg eq '-t') { $silence_timeout = shift @ARGV // 0 }
        elsif ($arg eq '-T') { $hard_timeout    = shift @ARGV // 0 }
        elsif ($arg eq '-q') { $quiet           = 1 }
        elsif ($arg eq '-n') { $ring_size       = shift @ARGV // 100 }
        elsif ($arg eq '-v') { $verbose         = 1 }
        elsif ($arg eq '-h' || $arg eq '--help') { usage() }
        elsif ($arg eq '--') { last }
        else { usage("unknown option: $arg") }
    }
}

sub usage {
    my $err = $_[0] ? "Error: $_[0]\n\n" : "";
    die "${err}Usage: suck [-t SEC] [-T SEC] [-q] [-n N] [-v] [command [args...]]

Pipe fitting that kills on silence.

Options:
  -t SEC   Silence timeout. Kill if no output for SEC seconds. [0=off]
  -T SEC   Hard timeout. Kill after SEC seconds regardless.   [0=off]
  -q       Quiet mode. Buffer output, only show on timeout.
  -n N     Ring buffer size for -q mode.                      [100]
  -v       Verbose status to stderr.

Exit codes:
  0    Normal completion
  124  Hard timeout
  125  Silence timeout
  127  Exec failed

Examples:
  perlbrew install-cpanm | suck -t 60
  suck -t 30 -T 3600 make -j4
  suck -t 60 -q -n 50 ./slow-build.sh
  cpanm DBI | suck -t 10 -v
\n";
}

# thankyuoverymuchGoodnight
exit 0;


